jw_shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('store.urls')),
    path('search/', include('search.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #이미지업로드

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]    

store/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
  #클래스 뷰
  path('', views.StoreView.as_view(), name="store"),
  path('cart/', views.CartView.as_view(), name="cart"),
  path('checkout/', views.CheckoutView.as_view(), name="checkout"),
  path('update_item/', views.UpdatedItemView.as_view(), name="update_item"),

  #함수형 뷰
  #path('', views.store, name="store"),
  #path('cart/', views.cart, name="cart"),
  #path('checkout/', views.checkout, name="checkout"),
  #path('update_item/', views.updatedItme, name="update_item"),
  path('process_order/', views.processOrder, name="process_order"),

  path('register/', views.RegistrationView.as_view(), name="register"),
  path('login/', auth_views.LoginView.as_view(template_name="store/login.html"), name="login"),
  path('logout/', auth_views.LogoutView.as_view(), name="logout"),
  path('product/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
  path('add-product/', views.ProductAddView.as_view(), name="add_product"),
  path('product/<int:pk>/add_comment/', views.add_comment, name="add_comment"),
  path('product/<int:pk>/remove_comment/', views.remove_comment, name="remove_comment"),
  path('product/<int:pk>/modify_comment/', views.modify_comment, name="modify_comment"),

]

store/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

class Customer(models.Model):
  user = models.OneToOneField(User,null=True, blank=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=200, null=True)
  email = models.CharField(max_length=200)
  def __str__(self):
    return self.name

class Product(models.Model):
  name = models.CharField(max_length=200)
  description = models.CharField(max_length=200)
  price = models.IntegerField(default=0)
  digital = models.BooleanField(default=False, null=True, blank=True)
  image = models.ImageField(null=True, blank=True)
  
  def __str__(self):
    return self.name
  @property
  def imageURL(self):
    try:
      url = self.image.url
    except:#사진없으면
      url = '/images/이미지없음.png'
    return url

  
class Order(models.Model):
  customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True )
  dated_ordered =models.DateTimeField(auto_now_add=True) #에러수정
  complete = models.BooleanField(default=False, null=True, blank=True)
  transation_id = models.CharField(max_length=200, null=True)
  def __str__(self):
    return str(self.id)
  @property
  def shipping(self):
    shipping = False
    orderitems = self.orderitem_set.all()
    for i in orderitems:
      if i.product.digital == False:
        shipping = True
    return shipping
  @property
  def get_cart_total(self): #장바구니 총 가격
    orderitems = self.orderitem_set.all()
    total = sum([item.get_total for item in orderitems])
    return total  
  def get_cart_items(self): #장바구니 총 가격
    orderitems = self.orderitem_set.all()
    total = sum([item.quantity for item in orderitems])
    return total


class OrderItem(models.Model):
  product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
  order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
  quantity = models.IntegerField(default=0, null=True, blank=True)
  dated_added = models.DateTimeField(auto_now_add=True)

  @property
  def get_total(self): #해당 아이템 개수에대한 총 가격
    total = self.product.price * self.quantity
    return total


class ShippingAddress(models.Model):
  customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
  order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
  address = models.CharField(max_length=200, null=True)
  city = models.CharField(max_length=200, null=True)
  state = models.CharField(max_length=200, null=True)
  zipcode = models.CharField(max_length=200, null=True)
  dated_added = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return self.address+'/'+self.city+'/'+self.state+'/'+self.zipcode


@receiver(post_save, sender=User) #시그널 회원가입 저장
def create_or_update_customer(sender, instance, created, **kwargs):
  if created:
    Customer.objects.create(user=instance, name=instance.username, email=instance.email)
  instance.customer.save()



#댓글
class Comment(models.Model):
  product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE )
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  text = models.TextField()
  created_date = models.DateTimeField(default=timezone.now)
  modify_date = models.DateTimeField(null=True, blank=True)
  approved_comment = models.BooleanField(default=True) #댓글승인
  def __str__(self):
    return self.text

store/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = '__all__'


#회원가입폼
class CreateUserForm(UserCreationForm):
  email = forms.EmailField(required=True)
  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")
  def save(self, commit=True):
    user = super(CreateUserForm, self).save(commit=False)
    user.email = self.cleaned_data["email"]
    if commit:
      user.save()
    return user


#댓글작성폼
class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['text']
    labels = {
      'text': '댓글',
    }

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import *
import json, datetime
from . cookie import *
from django.views.generic import CreateView, DetailView, TemplateView, View
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages


####상점
def store(request):
  Data = cart_data(request) # cookie.py > def cookie_cart
  cartItems = Data['cartItems']
  products = Product.objects.all()

  context={'products': products, 'cartItems': cartItems}
  return render(request, 'store/상점.html', context) #앱의 템플릿폴더를 자동인식하기때문에 경로이럼.
class StoreView(TemplateView):
  template_name = "store/상점.html"
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    Data = cart_data(self.request)
    cartItems = Data['cartItems']
    products = Product.objects.all()
    context={'products': products, 'cartItems': cartItems}
    return context


####장바구니
def cart(request):
  Data = cart_data(request) # cookie.py > def cookie_cart
  cartItems = Data['cartItems']
  order = Data['order']
  items = Data['items']

  context = {'items': items, 'order':order, 'cartItems': cartItems }
  return render(request, 'store/장바구니.html', context)
class CartView(TemplateView):
  template_name = "store/장바구니.html"
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    Data = cart_data(self.request)
    cartItems, order, items= Data['cartItems'], Data['order'], Data['items']
    context = {'items': items, 'order':order, 'cartItems': cartItems }
    return context
    

####결제
def checkout(request):
  Data = cart_data(request) # cookie.py > def cookie_cart
  cartItems = Data['cartItems']
  order = Data['order']
  items = Data['items']

  context = {'items': items, 'order':order, 'cartItems': cartItems}
  return render(request, 'store/결제.html', context)
class CheckoutView(TemplateView):
  template_name = "store/결제.html"
  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      Data = cart_data(self.request)
      cartItems = Data['cartItems']
      order = Data['order']
      items = Data['items']
      context = {'items': items, 'order':order, 'cartItems': cartItems}
      return context


######장바구니 수량 업데이트
def updatedItme(request):
  data = json.loads(request.body) #제이슨타입의 데이터 가져오기 (바디에있는)
  productID = data['productID']
  action = data['action']

  customer = request.user.customer
  product = Product.objects.get(id=productID)
  order, created = Order.objects.get_or_create(customer=customer, complete=False)
  orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
  if action == 'add':
    orderItem.quantity += 1
  elif action == 'sub':
    orderItem.quantity -= 1
  
  orderItem.save()
  if orderItem.quantity <= 0:
    orderItem.delete()

  return JsonResponse('Item added zz', safe=False)
class UpdatedItemView(View):
  def post(self, request, *args, **kwargs):
    data = json.loads(request.body) #제이슨타입의 데이터 가져오기 (바디에있는)
    productID = data['productID']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productID)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    if action == 'add':
      orderItem.quantity += 1
    elif action == 'sub':
      orderItem.quantity -= 1
    
    orderItem.save()
    if orderItem.quantity <= 0:
      orderItem.delete()
    return JsonResponse('Item added zz', safe=False)




########################################
@csrf_exempt #csrf 에러 방지


##################
def processOrder(request):
  transation_id = datetime.datetime.now().timestamp()
  data = json.loads(request.body)

  if request.user.is_authenticated:
    customer = request.user.customer
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    
  else: #미사용자의 결제
    customer, order = client_order(request, data)

  total = int(data['user_form']['total'])
  order.transation_id = transation_id

  if total == order.get_cart_total:
      order.complete = True
  order.save()
  if order.shipping == True:
      ShippingAddress.objects.create(
          customer = customer,
          order = order,
          address = data['shipping']['address'],
          city = data['shipping']['city'],
          state = data['shipping']['state'],
          zipcode = data['shipping']['zipcode'],
  )     

  return JsonResponse('Payment Completed!', safe =False) 


class RegistrationView(CreateView):
  template_name = "store/registration.html"
  #form_class = UserCreationForm
  form_class = CreateUserForm
  success_url = "/"


class ProductDetailView(DetailView):
  template_name = "store/product_detail.html"
  queryset = Product.objects.all()
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    Data = cart_data(self.request)
    cartItems = Data['cartItems']
    context['cartItems'] = cartItems
    return context #장바구니 개수 업데이트위해



######
class ProductAddView(CreateView):
  form_class = ProductForm
  template_name = "store/add_product.html"
  success_url = "/"



#댓글
def add_comment(request, pk):
  product = get_object_or_404(Product, pk=pk)
  if request.method == "POST":
    form = CommentForm(request.POST)
    if form.is_valid():
      comment=form.save(commit=False)
      comment.author = request.user
      comment.product = product
      comment.save()
      return redirect('product_detail', pk=product.pk)
  else:
    form = CommentForm()
  return render(request, 'store/add_comment.html', {'form': form})


@login_required
def modify_comment(request, pk):
  comment = get_object_or_404(Comment, pk=pk)
  if request.method == "POST":
    form = CommentForm(request.POST, instance=comment)
    if form.is_valid():
      comment = form.save()
      comment.modify_date = timezone.now()
      comment.save()
      return redirect('product_detail', pk=comment.product.pk)
  else:
    form = CommentForm(instance=comment)
  return render(request, 'store/add_comment.html', {'form': form})


@login_required
def remove_comment(request, pk):
  comment = get_object_or_404(Comment, pk=pk)
  comment.delete()
  return redirect('product_detail', pk=comment.product.pk)

store/templates/store/add_comment.html
{% extends 'store/base.html'%}
{% load static %}
{% block content %}
    <h1>댓글 작성하기</h1>
    <form method="POST" class="post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">쓰기</button>
    </form>
{% endblock %}

store/templates/store/add_product.html
{% extends 'store/base.html'%}
{% load static %}
{% block content %}
<h3>-제품등록-</h3>
<div class="row">
    <div class="col-lg-6">
        <div class="box">
            <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary">등록</button>
            </form>
        </div>

    </div>
</div>

{% endblock content %}

store/templates/store/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>재운's Market</title>


  <!-- css 순서 지키키 ! (적용순이 달라짐)-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">



  <script type ="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  const csrftoken = getToken('csrftoken');

  function getCookie(name) {
// 쿠키 문자열을 분할하고 배열의 모든 개별 이름 = 값 쌍을 가져옵니다.
    var cookieArr = document.cookie.split(";");
    // 배열 요소를 통해 반복
    for(var i = 0; i < cookieArr.length; i++) {
        var cookiePair = cookieArr[i].split("=");
        /* 쿠키 이름 시작 부분의 공백 제거 주어진 문자열과 비교 */
        if(name == cookiePair[0].trim()) {
            // 쿠키 값을 디코딩하고 반환
            return decodeURIComponent(cookiePair[1]);
        }
    }
        // 찾을 수없는 경우 null 반환
        return null;
  }

  //장바구니 쿠키 생성
  var cart = JSON.parse(getCookie('cart'))
  if (cart == undefined) {
    cart = {}
    document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
  }

  </script>



</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'store' %}">재운's Market</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">빈 메뉴</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              세부사항
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'add_product' %}">제품등록</a></li>
              <li><a class="dropdown-item" href="#">빈 메뉴</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">빈 메뉴</a></li>
            </ul>
          </li>
        </ul>
      
        <div class="form-inline my-2 my-lg-0 text-red">
          <a href="{% url 'cart' %}" style="text-decoration:none; color:rgb(187, 53, 165)">
            <span class="text-red"><strong>cart items: {{cartItems}}</strong></span>
            <img src="{% static 'images/장바구니이미지1.png' %}" >
          </a>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-light">{{user.username}}님 로그아웃</a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-light">로그인</a>
          <a href="{% url 'register' %}" class="btn btn-light">회원가입</a>
        {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <nav id="searchform2">
    <!--제품이름과 제품설명이용해 검색-->
      <form class="form-inline searchform3" action="{% url 'search:searchResult' %}" method="get">
        <input class="form-control mr-sm-2 " type="search" placeholder="검색" name="kw">
      </form> 
  </nav>

  <br>
  <div class="container">
    <p>
    {% block content %}


    {% endblock content %}
  </div>

  <!-- JavaScript Bundle with Popper -->
  <!-- 햄버거 메뉴 미작동 에러시, (부트스트랩 버전 에러)
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

store/templates/store/login.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
      <div class="box">
          <form action="." method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary">로그인</button>
          </form>
      </div>
  </div>
</div>



{% endblock content %}

store/templates/store/product_detail.html
{% extends 'store/base.html'%}
{% load static %}
{% block content %}
<h3>제품명 : {{ product.name }}</h3>
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
      <article class="gallery-wrap"> 
        <div class="img-big-wrap">
          <div> <a href="#"><img src="{{ product.imageURL }}" class="img-fluid"></a></div>
        </div>
      </article>
    </aside>
    
    <aside class="col-sm-7">
      <article class="card-body p-5">
        <h3 class="title mb-3">{{ product.name }}</h3>
          <p class="price-detail-wrap"> 
            <span class="price h3 text-warning"> 
              <span class="currency"></span><span class="num">{{ product.price }}\</span>
            </span> 
          </p> <!-- price-detail-wrap .// -->
        <dl class="item-property">
          <dt>제품설명</dt>
          <dd><p>{{ product.description }} </p></dd>
        </dl>  
        <hr>
          <button data-product={{product.id}} data-action="add" class="btn btn-success 장바구니업데이트">장바구니 담기</button>
        <hr>
        {% for comment in product.comments.all %}
          {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
              <div class="editcomment">
                {{comment.created_date}}
                  {% if comment.modify_date %}
                  [수정: {{comment.modify_date}}]
                  {% endif %}

                  {% if request.user == comment.author %}
                  <a href="{% url 'modify_comment' pk=comment.pk  %}" class="small">수정</a>,
                  <a href="{% url 'remove_comment' pk=comment.pk  %}" class="small">삭제</a>
                  {% endif %}
              </div>

              <strong>{{comment.author}}</strong>
              <p> {{comment.text|linebreaks}}</p>
              <hr>
            </div>
          {% endif %}
          {% empty %}
          <p>댓글이 없습니다.</p>
        {% endfor %}

        {% if user.is_authenticated %}
          <a class="btn btn-success" href="{% url 'add_comment' pk=product.pk %}">댓글작성</a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-danger">로그인 후 댓글달기</a>
        {% endif %}
        </article> <!-- card-body.// -->
    </aside> <!-- col.// -->
  </div> <!-- row.// -->
</div> <!-- card.// -->

{% endblock content %}

store/templates/store/registration.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
      <div class="box">
          <form action="." method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary">가입하기</button>
          </form>
      </div>
  </div>
</div>



{% endblock content %}

store/templates/store/결제.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div id="배송전체폼" class="box">
            <form id="배송정보폼">
                <div id="사용자정보">
                    <div>
                        <input required class="form-control" type="text" name="name" placeholder="성함..">
                    </div>
                    <div>
                        <input required class="form-control" type="email" name="email" placeholder="이메일..">
                    </div>
                </div>

                <div id="배송정보">
                    <hr>
                    <p>배송 정보:</p>
                    <div>
                        <input class="form-control" type="text" name="address" placeholder="주소..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="city" placeholder="도시..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="state" placeholder="도..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="zipcode" placeholder="우편 번호..">
                    </div>
                    <div>
                        <input class="form-control" type="text" name="country" placeholder="국가..">
                    </div>
                </div>

                <hr>
                <input id="배송정보폼버튼" class="btn btn-secondary btn-block" type="submit" value="❗ 배송정보 제출하기">
            </form>
        </div>

        <br>
        <div class="box 숨기기" id="payment-info">
            <!--<button id="make-payment" class="btn btn-secondary">💰 결제 하기</button>-->
            <div id="paypal-button-container"></div>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box">
            <a class="btn btn-outline-secondary" href="{% url 'cart' %}">
                <img width=20 src="{% static 'images\reply-shop.png' %}">장바구니로 돌아가기</a>
            <hr>
            <h3>주문 요약</h3>
            <hr>

            {% for item in items %}
            <div class="장바구니줄">
                <div style="flex:2"><img class="장바구니이미지" src="{{item.product.imageURL}}"></div>
                <div style="flex:2"><strong>{{item.product.name}}</strong></div>
                <div style="flex:1"><strong>개당{{item.product.price}}</strong></div>
                <div style="flex:1"><strong>{{item.quantity}}</strong></div>
            </div>
            {% endfor %}
            <h5>제품 수:{{order.get_cart_items}} </h5>
            <h5>총합: \{{order.get_cart_total}}</h5>
        </div>
    </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=AbcOIE-B_thQ80lmYvDesXmjU9fM9jP4sq0Phg4uqNqdDz_kPGvTse4WB2pM9q62C0AKJb-z6UhESLtW&currency=USD"></script>
<script>
    var total = '{{order.get_cart_total}}' //총금액

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({
        style: {
            color:  'blue',
            shape:  'pill',
            label:  'pay',
            height: 40
        },
        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseInt(total)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(order Data) {
                // Successful capture! For demo purposes:
                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                submitFormData()
                // Replace the above to show a success message within this page, e.g.
                // const element = document.getElementById('paypal-button-container');
                // element.innerHTML = '';
                // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                // Or go to another URL:  actions.redirect('thank_you.html');
            });
        }

        // Render the PayPal button into #paypal-button-container
    }).render('#paypal-button-container');
</script>

<script type = "text/javascript">
    var shipping = '{{order.shipping}}'   
    var total = '{{order.get_cart_total}}' //총금액

    if (shipping == 'False'){ //온라인 제품구매 시,
        document.getElementById('배송정보').innerHTML = ''
    }
    if (user != 'AnonymousUser'){  //로그인시, 사용자입력정보 생략
        document.getElementById('사용자정보').innerHTML = ''
    }   
    if (shipping == 'False' && user != 'AnonymousUser'){  //온라인제품구매+ 로그인 중일시, 배송전체 생략
        document.getElementById('배송전체폼').classList.add('숨기기')
        document.getElementById('payment-info').classList.remove('숨기기')
    }    


    var shipp_form = document.getElementById('배송정보폼') //배송정보 입력시, 정보창 생략
    shipp_form.addEventListener('submit', function(e) {
        e.preventDefault()
        document.getElementById('배송정보폼버튼').classList.add('숨기기') //css이용
        document.getElementById('payment-info').classList.remove('숨기기') //
    })
    /*
    document.getElementById('make-payment').addEventListener('click', function(e){ //결제누를시,
        submitFormData()
    })*/  

    function submitFormData() {
        alert('주문되었습니다.')
        var userFormData = {
            'name' :null,
            'email' :null,
            'total' : (total),
        }

        var shippingInfo = {
            'address' :null,
            'city' :null,
            'state' :null,
            'zipcode' :null,
        }
        
        if (shipping != 'False') { //온라인제품아니면
            shippingInfo.address = shipp_form.address.value
            shippingInfo.city = shipp_form.city.value
            shippingInfo.state = shipp_form.state.value
            shippingInfo.zipcode = shipp_form.zipcode.value
        }
        if (user == 'AnonymousUser'){ //미로그인시,  (user변수 베이스에서가져옴)
            //로그인시는 이미 정보가 있으므로
            userFormData.name = shipp_form.name.value
            userFormData.email = shipp_form.email.value
        }

        var url ='/process_order/'
        fetch(url,{ //패치 이용 (정보 전송)
            method: 'POST', //전송방식(업데이트)
            headers: { //헤더 포함내용
                'Content-Type':'application/json',
                'X-CSRFToken': csrftoken //패치 해킹방지 (csrf토큰, base에서 가져옴)
            },
            body: JSON.stringify({'user_form': userFormData, 'shipping': shippingInfo}) //바디 내용
        })
        .then((response)=>{ //응답받으면 (데이터를 받음)
            return response.json() 
        })
        .then((data)=>{ //받은 데이터 활용
            alert('주문이 완료 되었습니다.');
            cart = {} //장바구니 리셋
            document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/" //쿠키 리셋
            window.location.href= "{% url 'store' %}"
        })

    }
</script>
{% endblock content %}